# =============================================================================
# api/models.py
# Pydantic response schemas for the FastAPI query layer.
#
# Each model maps to one gold-layer DuckDB table.  Field names use snake_case
# (the JSON convention) which is distinct from the mixed-case DuckDB column
# names — the SQL queries in app.py alias columns to match these field names.
#
# All models use Pydantic v2 (ships with FastAPI >= 0.100).
# =============================================================================

from pydantic import BaseModel  # Base class for all Pydantic v2 models

# =============================================================================
# /sales/regions  →  agg_sales_by_region
# =============================================================================


class RegionSales(BaseModel):
    """One row per US sales region with revenue and profitability KPIs."""

    region: str  # Sales region name (East / West / Central / South)
    total_sales: float  # Aggregate revenue for all orders in this region
    total_profit: float  # Aggregate net profit (negative = loss-making region)
    total_orders: int  # Count of distinct order IDs placed in this region
    avg_discount: float  # Mean discount rate applied across all line items
    avg_profit_margin: float  # Mean profit margin percentage across all line items


# =============================================================================
# /sales/trends  →  agg_monthly_trends
# =============================================================================


class MonthlyTrend(BaseModel):
    """One row per calendar month with aggregated sales and volume metrics."""

    order_year: int  # Four-digit year (2014 – 2017)
    order_month: int  # Month number (1 = January … 12 = December)
    order_month_name: str  # Month name string (e.g. "November")
    total_sales: float  # Total revenue for this month
    total_profit: float  # Total net profit for this month
    total_orders: int  # Distinct orders placed in this month
    total_units: int  # Total units sold across all orders this month


# =============================================================================
# /products/top  →  agg_product_performance
# =============================================================================


class ProductPerformance(BaseModel):
    """One row per product SKU ranked by total sales revenue."""

    product_id: str  # Unique product identifier (e.g. TEC-MA-10002412)
    product_name: str  # Full product display name
    category: str  # Top-level product category (Furniture / Office Supplies / Technology)
    sub_category: str  # Sub-category within the parent category
    total_sales: float  # Lifetime revenue generated by this product
    total_profit: float  # Lifetime net profit generated by this product
    total_orders: int  # Number of distinct orders containing this product
    avg_profit_margin: float  # Average profit margin percentage across all transactions


# =============================================================================
# /segments  →  agg_customer_segments
# =============================================================================


class CustomerSegment(BaseModel):
    """One row per customer segment with acquisition and revenue KPIs."""

    segment: str  # Customer segment (Consumer / Corporate / Home Office)
    total_customers: int  # Count of unique customers in this segment
    total_orders: int  # Total distinct orders placed by this segment
    total_sales: float  # Total revenue generated by this segment
    total_profit: float  # Total net profit generated by this segment
    avg_order_value: float  # Average line-item revenue across all orders
    avg_profit_margin: float  # Average profit margin percentage across all transactions
